[package]
name = "AVL_Tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "AVL_Tree"
path = "src/lib.rs"
[dependencies]
binary_lib = {path = "../binary_lib"}

